const env = {
  API_KEY: "APP_KEY_HERE",
  AUTH_DOMAIN: "AUTH_DOMAIN_HERE",
  PROJECT_ID: "PROJECT_ID_HERE",
  STORAGE_BUCKET: "STORAGE_BUCKET_HERE",
  MESSAGING_SENDER_ID: "MESSAGING_SENDER_ID_HERE",
  APP_ID: "APP_ID_HERE",
  MEASUREMENT_ID: "MEASUREMENT_ID_HERE",
};

export default env;
